#!/bin/bash
# This script for downloading logs from server to local directory.


# Define directory name.
LOCALDIR="LOG`date +%Y%m%d_%H%M%S`"

# If directory doesn't exist, create it.
test -d $LOCALDIR || mkdir -p $LOCALDIR/Reader

# Create soft link to the neweast log directory.
ln -sf $LOCALDIR LOG

# Download APP log.
scp 172.16.16.15:/media/data/log/APP_LOG ./$LOCALDIR


ReaderLogDir="/home/nemochen/GateSystem/log"
ReaderLog[0]="Application.txt"
ReaderLog[1]="EntryReader.txt"
ReaderLog[2]="ExitReader.txt"
ReaderLog[3]="Mode.txt"
ReaderLog[4]="TicketProcessing.txt"


for (( i = 0; i < ${#ReaderLog[@]}; i++ )); do
	if (( i == 0 )); then
		ReaderLogFiles+="${ReaderLog[i]}"
	else
		ReaderLogFiles+=",${ReaderLog[i]}"
	fi
done

# Download Reader log.
scp 172.16.16.15:$ReaderLogDir/{$ReaderLogFiles} ./$LOCALDIR/Reader